uniform_company_name = {
    "AGL Energy":"AGL Energy Ltd",
    "Adani Group":"Adani Group",
    "Alliance Resource Partners":"Alliance Resource Partners LP",
    "Amplify Energy":"Amplify Energy Corp",
    "Anhui Xinji Coal and Electricity Group China COSCO Shipping":"Anhui Province Wanbei Coal-Electricity Group Co Ltd",
    "Arch Resources":"Arch Resources Inc",
    "BHP":"BHP Group Ltd",
    "BP":"BP PLC",
    "BP P.L.C.":"BP PLC",
    "Bayan Resources":"Bayan Resources Tbk PT",
    "Beijing Energy":"Beijing Energy Holding Co Ltd",
    "Beijing Energy Group":"Beijing Energy Holding Co Ltd",
    "Bulgarian Energy Holding":"Bulgarian Energy Holding EAD",
    "Chevron":"Chevron Corp",
    "Chevron Corporation":"Chevron Corp",
    "China COSCO Shipping":"China COSCO Shipping Corp Ltd",
    "China Coal":"China Coal Xinji Energy Co Ltd",
    "China Datang":"China Datang Corp",
    "China Energy":"China Energy Investment Corp Ltd",
    "China Energy Investment Corporation":"China Energy Investment Corp Ltd",
    "China Huadian":"China Huadian Corp Ltd",
    "China Huadian Group":"China Huadian Corp Ltd",
    "China Huaneng":"China Huaneng Group Co Ltd",
    "China National Petroleum Corporation":"China National Petroleum Corporation (CNPC)",
    "China ZhenHua Oil Co.":"China ZhenHua Oil Co Ltd",
    "Coal India":"Coal India Ltd",
    "ConocoPhillips":"ConocoPhillips",
    "Delek Group":"Delek Group Ltd",
    "Devon Energy":"Devon Energy Corp",
    "EOG Resources":"EOG Resources Inc",
    "Elion Group":"Elion Resources Group Ltd",
    "Endeavor Energy Resources":"Endeavor Energy Resources LP",
    "Ensign Operating":"Ensign Operating LLC",
    "Equinor ASA":"Equinor ASA",
    "Euas Electricity Generation Company (Elektrik Üretim A.Ş, EÜAŞ)":"Electricity Generating PCL",
    "Evraz":"Evraz PLC",
    "Exxaro":"Exxaro Resources Ltd",
    "ExxonMobil Corporation":"Exxon Mobil Corp",
    "Gazprom":"Gazprom PJSC",
    "Glencore":"Glencore PLC",
    "Guangdong Hanjian Holding Company":"Guangdong Hanjian Investment Co Ltd",
    "Guangdong Hengjian Investment Holding Company":"Guangdong Hengjian Investment Holding Co Ltd",
    "Harbour Energy plc":"Harbour Energy PLC",
    "HeBei Construction & Investment Group":"Hebei Construction & Investment Group Co Ltd",
    "Hebei Construction & Investment Group":"Hebei Construction & Investment Group Co Ltd",
    "Hess Corporation":"Hess Corporation",
    "Huayang New Material Technology Group":"Huayang New Material Technology Group Co Ltd",
    "Hubei Yihua Chemical Company":"Hubei Yihua Chemical Industry Co Ltd",
    "INPEX Corporation":"Inpex Corp",
    "ITOCHU Corporation":"ITOCHU Corp",
    "Indian Oil Corporation Limited":"Indian Oil Corp Ltd",
    "Indika Energy":"Indika Energy Tbk PT",
    "Indonesia Asahan Aluminium":"Indonesia Asahan Aluminium Persero PT",
    "Inner Mongolia Mengtai Group":"Inner Mongolia Mengtai Group Co Ltd",
    "Inner Mongolia Yitai Group":"Inner Mongolia Yitai Investment Co Ltd",
    "Inner Mongolia Yitai Investment":"Inner Mongolia Yitai Investment Co Ltd",
    "Jinneng Group":"Jinneng Holding Group Co Ltd",
    "Jinneng Holding Group":"Jinneng Holding Group Co Ltd",
    "Jizhong Energy Group":"Jizhong Energy Group Co Ltd",
    "Kailuan Group":"Kailuan Group Ltd Liability Corp",
    "Kuwait Petroleum Corporation":"Kuwait Petroleum Corp",
    "Lu'an Chemical Group":"Lu'an Chemical Group Co Ltd",
    "Marathon Oil Company":"Marathon Oil Corp",
    "Mitsubishi Corporation":"Mitsubishi Corp",
    "NTPC":"NTPC Ltd",
    "Occidental Petroleum Corporation":"Occidental Petroleum Corp",
    "POSCO":"POSCO Holdings Inc",
    "PPL":"PPL Corp",
    "PT Pertamina":"Pertamina Persero PT",
    "Peabody Energy":"Peabody Energy Corp",
    "Petrobras":"Petróleo Brasileiro SA – Petrobras",
    "Petroleos Mexicanos":"Petróleos Mexicanos (PEMEX)",
    "Pioneer Natural Resources":"Pioneer Natural Resources Co",
    "QatarEnergy":"QatarEnergy",
    "Qatargas Operating Company Limited":"QatarEnergy",
    "ROSNEFTEGAZ JSC":"Rosneftegaz AO",
    "Reliance Power":"Reliance Power Ltd",
    "Repsol SA":"Repsol SA",
    "SM Energy Company":"SM Energy Co",
    "Saudi Aramco":"Saudi Arabian Oil Company (Saudi Aramco)",
    "Shaanxi Coal and Chemical Group":"Shaanxi Coal and Chemical Industry Group Co Ltd",
    "Shaanxi Coal and Chemical Industry Group":"Shaanxi Coal and Chemical Industry Group Co Ltd",
    "Shaanxi Investment Group":"Shaanxi Investment Group Co Ltd",
    "Shaanxi Yanchang Petroleum Group":"Shaanxi Yanchang Petroleum Group Co Ltd",
    "Shaanxi Yanchang Petroleum and Mining Company":"Shaanxi Yanchang Petroleum Group Co Ltd",
    "Shaanxi Yulin Energy Group":"Shaanxi Yulin Energy Group Co Ltd",
    "Shandong Energy":"Shandong Energy Co Ltd",
    "Shanxi Coking Coal Group":"Shanxi Coking Coal Group Co Ltd",
    "Shell plc":"Shell PLC",
    "Shenergy":"Shenergy Group Co Ltd",
    "Shenmu City State-Owned Assets Operation Company":"Shenmu City State-Owned Assets Operation Co",
    "Shenmu County State-Owned Asset Management Company":"Shenmu City State-Owned Assets Operation Co",
    "Shenmu County State-Owned Assets Operation Company":"Shenmu City State-Owned Assets Operation Co",
    "Shenmu State-Owned Assets Operation Company":"Shenmu City State-Owned Assets Operation Co",
    "Shougang Group":"Shougang Group Co Ltd",
    "Sojitz":"Sojitz Corp",
    "State Grid Company":"State Grid Corp of China",
    "State Grid Corporation of China":"State Grid Corp of China",
    "Teck Resources":"Teck Resources Ltd",
    "Thungela Resources Australia":"Thungela Resources Ltd",
    "Tianjin Energy Investment Group":"Tianjin Energy Investment Co Ltd",
    "Titan Infra Energy":"Titan Infra Energy PT",
    "TotalEnergies":"TotalEnergies SE",
    "Xinjiang Guanghui Industry Investment Group":"Xin Jiang Guang Hui Industry Investment Group Co Ltd",
    "Yangcheng County Yangtai Group":"Yangcheng County Yangtai Group Industrial Co Ltd",
    "Zhejiang Energy Group":"Zhejiang Provincial Energy Group Co Ltd",
}
