# Dictionnary for Coal Mine only
manual_match_coal = {
    "Maritsa Coal Mines":"Troyanavo 3 Coal Mine",
    "Kaniha Coal Mine":"Gopalji Kaniha Coal Mine",
    "Kerandari BC":"Kerendari Coal Mine",
    "Bankui":"Barkui Coal Mine",
    "Mandakini B":"Mandakini–B Coal Mine",
    "Saharpur Jamarpani":"Saharpur-Jamarpani Coal Mine",
    "BIB Coal Mine":"Boneo Indobara Coal Mine",
    "Borly Coal Mines":"Molodezhny Coal Mine",
    "Listvianskaya Coal Mine":"Listvyazhnaya Coal Mine",
    "Elga Coal Mine":"Elginskiy Coal Mine",
    "Inaglinskaya-2 Mine":"Inaglinsky Coal Mine 2",
    "Bernice-Cygnus Coal Mine":"Berenice-Cygnus Coal Mine",
    "Hamilton County Mine No.1":"White Oak Coal Mine",
    "Sengwe Colliery":"Sengwa Coal Mine",
}

# Dictionnary for Gas and Oil only
manual_match_gasoil = {
    "Bu Hasa":"Bu Hasa/Shah/Asab",
    "Bab":"None",
    "Umm Shaif/Nasr":"Umm Shaif",
    "Bab (Gasco)":"None",
    "Asab":"Bu Hasa/Shah/Asab",
    "Vaca Muerta Shale":"None",
    "Goldwyer Shale":"None",
    "Gorgon LNG T1-T3":"None",
    "Velkerri Shale":"None",
    "ACG (Azeri-Chirag-Guneshli Deep Water)":"Azeri-Chirag-Guneshli (ACG) Deepwater",
    "Central Arabian Offshore":"None",
    "Santos Offshore":"None",
    "Llandovery Shale":"None",
    "Buzios (x-Franco)":"Búzios",
    "Irati Shale":"None",
    "Lula (X-Tupi)":"Tupi",
    "Parnaiba Onshore":"None",
    "Candeias Shale":"Candeias",
    "Mero (Libra NW)":"Libra",
    "Montney Play":"Northern Montney",
    "Spirit River (Notikewin, Falher, Wilrich)":"None",
    "Horizon Oil Sands Project":"None",
    "Kearl":"None",
    "Duvernay":"None",
    "Athabasca Oil Sands Project":"Athabasca Area - Scheme 9241H Oil Sands",
    "Christina Lake":"None",
    "Liard Shale":"None",
    "Syncrude Mildred Lake/Aurora":"Athabasca Area - Scheme 8573P Oil Sands",
    "Longmaxi Shale":"None",
    "Daqing":"None",
    "Cambrian/Silurian Marine Shale":"None",
    "Longmaxi Shale (Sichuan/Changyu)":"West Sichuan",
    "Tarim (CNPC)":"Tarim",
    "Southeast Uplift Onshore Heilongjiang Province":"None",
    "Oil shale China":"None",
    "Xinjiang (CNPC)":"None",
    "Central Uplift Onshore Xinjiang Uygur Autonomous Region":"None",
    "La Luna Shale":"None",
    "Tannezuft Shale":"None",
    "Hassi R'Mel (Domestic)":"Hassi R'Mel",
    "Bowland Shale":"None",
    "Kronprins Christian Offshore":"None",
    "Greater Turbot (Stabroek)":"Stabroek",
    "Greater Liza (Liza)":"None",
    "East Natuna (x-Natuna D-Alpha)":"Anoa",
    "Barail Shale":"None",
    "Rumaila North & South":"Rumaila",
    "Qurna West":"Qurna West 1",
    "Baghdad East":"East Baghdad",
    "Central Arabian Onshore":"None",
    "Qurna West-2":"Qurna West 2",
    "Halfayah":"Halfaya",
    "Nahr bin Umar":"Nahr Bin Umar",
    "Basrah Gas project":"Zubair",
    "Azadegan":"Azadegan North",
    "Ahwaz Asmari":"Ahvaz-Asmari",
    "Central Arabian Offshore":"None",
    "Agha Jari":"Aghajari",
    "Ahwaz Bangestan":"Ahvaz-Bangestan",
    "South Pars (Phases 9-10) dry gas":"South Pars (Phase 9-10)",
    "Kish Gas Project":"Kish",
    "Pars Southwest":"None",
    "South Pars (Phases 4-5) dry gas":"South Pars (Phase 4-5)",
    "Mansouri Bangestan":"Mansouri",
    "South Pars (Phases 22-24)":"South Pars (All Phases)",
    "South Pars (Phases 20-21)":"South Pars (Phase 20-21)",
    "South Pars (Phases 2-3) dry gas":"South Pars (Phase 2-3)",
    "Project Kuwait":"None",
    "Central Arabian Onshore":"None",
    "Carboniferous Shale":"None",
    "Sirte Shale":"None",
    "Eagle Ford Shale":"None",
    "Gulf Deepwater Offshore":"None",
    "Ku-Maloob-Zaap":"Ku$Maloob$Zaap",
    "Yucatan Platform Offshore":"Akal$Nohoch$Chac",
    "MZLNG Joint Development":"None",
    "Area-1 Future Phases":"Area 4",
    "Area 1 LNG (T1&T2)":"Area 1",
    "NLNG Base Projec":"None",
    "Khafji":"Khafji",
    "Lublin Basin Silurian Shale":"Lubliniec-Cieszanów",
    "North Field C LNG":"North Field",
    "North Field E":"North Field Alpha",
    "QatarGas LNG T8-T11 (NFE-East)":"Qatargas 4",
    "Central Arabian Onshore":"None",
    "Qatargas 2 LNG T4-T5":"Qatargas 2",
    "QatarGas LNG T12-T13 (NFE-South)":"Qatargas 3",
    "Rasgas 2 LNG T3-T5":"RasGas Alpha",
    "Rasgas 3 LNG T6-T7":"RasGas Alpha",
    "QatarGas 1 LNG T1-T3":"Qatargas 3",
    "Al Khaleej Gas project":"Al Khalij",
    "Bovanenkovo Zone (Yamal Megaproject)":"Bovanenkovskoye",
    "Gazprom dobycha Yamburg":"Yamburgskoye",
    "Tunguska Basin CBM":"New",
    "Urengoyskoye":"Severo-Urengoyskoye",
    "Kuznetsk Depression (Kuzbass) CBM":"None",
    "Yuganskneftegaz":"Severo-Priobskoye",
    "Eastern Gas Program":"East Tazovskoye",
    "West Siberia Offshore":"West Surgutskoye",
    "Lensky Basin CBM":"None",
    "Timan - Pechora Basin Offshore":"None",
    "Tambey Zone (Yamal Megaproject)":"Yuzhno-Tambeyskoye",
    "Timan - Pechora Basin Onshore":"None",
    "Samotlorneftegaz (TNK-BP)":"Samotlorskoye",
    "Leningradskoye (Kara Sea)":"Leningradskoye",
    "Gazprom dobycha Orenburg":"Orenburgskoye",
    "Arctic LNG 2 T1-3":"New",
    "Volga - Urals Onshore":"None",
    "Romashkino":"Romashkinskoye",
    "Rusanovskoye (Kara Sea)":"None",
    "Gazprom dobycha Nadym":"Medvezhye$Bovanenkovskoye$Yamsoveiskoye",
    "Taymyr Basin CBM":"None",
    "North Kara Sea Offshore":"None",
    "West Siberia Onshore":"None",
    "SeverEnergia Project":"Samburgskoye",
    "Ghawar Uthmaniyah":"Ghawar",
    "Khurais project":"Khurais",
    "Ghawar Haradh":"Ghawar",
    "Central Arabian Offshore":"None",
    "Ghawar Shedgum":"Ghawar",
    "Qatif project":"Qatif",
    "Manifa (redevelop)":"Manifa",
    "Ghawar Hawiyah":"Ghawar",
    "Central Arabian Onshore":"None",
    "Zuluf (CR in field)":"Zuluf",
    "Ghawar Ain Dar N":"Ghawar",
    "Safaniya YTF Concession":"Safaniya",
    "Zuluf (expansion)":"Zuluf",
    "Ghawar Ain Dar S":"Ghawar",
    "Sudair Shale":"None",
    "Harmaliyah":"None",
    "Tanf Shale":"None",
    "Yolotan (Iolotan) South":"None",
    "Yashlar Vostochnyy (East)":"None",
    "Dovletabad-Donmez":"None",
    "Tanzanian Coastal Offshore":"None",
    "Menilite Shale":"None",
}

